### ISSUE TITLE
Config based on file extensions instead of profiles

### ISSUE THREAD

**Issue by RobertLang** [cmuench/inotify-proxy#5]
Hi,
we just recently discovered your project and it has helped us already in fixing those watcher issues under MacOS and Docker.
Unfortunately the profile definitions are a bit limited and are always missing the one or the other file type (for example *.scss in magento2)

So I would suggest to extend the configuration file to provide some sort ruleset for watched file extension:

---
watch:
  - dir: /tmp/watch1
  - dir: /tmp/watch2
extensions: 
  - "*.scss"
  - "*.js"
  - "*.twig"
  
  I think this would make it easier to specifically watch the files needed for different technology types instead of having to watch all files if none of the given profiles match.

Thanks for considering,
Robert

**Comment by cmuench** [comment]
@RobertLang Yes, hat a similar idea but currenlty less time to refactor the tool.

My idea was to allow extension configuration for each directory.

in this way:

```yaml

- dir: /tmp/watch1
  extensions:
  -  ".scss"
  - ".js"
  - ".twig"

- dir: /tmp/watch2
  extensions:
  -  ".foo"
  - ".bar"
  - ".js"
```

**Comment by cmuench** [comment]
@RobertLang New feature is released.
https://github.com/cmuench/inotify-proxy/releases/tag/2.0.0

Example Config:

```yaml
---
watch:
- directory: /tmp/watch1
  profile: magento2

- directory: /tmp/watch2
  profile: vue-storefront

- directory: /tmp/watch3
  extensions: [.css, .html]
```
